build:
  image: golang:1.6
#  environment:
#    - CGO_ENABLED=0
  commands:
    - go get ./...
    - make
    - make docs

cache:
  mount:
    - vendor

deploy:
  rsync:
    when:
      branch: master
    user: metalmatze
    host: matthiasloibl.com
    port: 1234
    source: docs/public/*
    target: web/matthiasloibl.com/gollection.matthiasloibl.com
    delete: true
    recursive: true
